/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frontera;

import Control.ArtistatJpaController;
import Control.EventotJpaController;
import Control.LugartJpaController;
import Entidad.Admint;
import Entidad.Artistat;
import Entidad.Eventot;
import Entidad.Lugart;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Armageddon132
 */
public class AdminApp extends javax.swing.JPanel {

    /**
     * Creates new form AdminApp
     */
    public HomeApp ha;
    public Admint adminS;
    private ArtistatJpaController artistaC = new ArtistatJpaController();
    private EventotJpaController eventoC = new EventotJpaController();
    private LugartJpaController lugarC = new LugartJpaController();
    private int placeId;
    private int artistId;

    public AdminApp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        Bg = new ImagePanel("C:\\Users\\Joan\\Documents\\NetBeansProjects\\ActividadesCulturales\\resources\\fondo2.jpg");
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        eventP = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        eventCreate = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        eventNameAddTF = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        eventPlaceAddTF = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        eventArtist1AddTF = new javax.swing.JComboBox();
        eventArtist2AddTF = new javax.swing.JComboBox();
        eventArtist3AddTF = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        eventCapacityAddTF = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        eventDateAddTF = new javax.swing.JTextField();
        addEventB = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        eventEdit = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        eventSelectorE = new javax.swing.JComboBox();
        jLabel21 = new javax.swing.JLabel();
        eventEditNameTF = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        eventEditPlaceTF = new javax.swing.JComboBox();
        jLabel23 = new javax.swing.JLabel();
        eventArtist1EditTF = new javax.swing.JComboBox();
        eventArtist2EditTF = new javax.swing.JComboBox();
        jLabel24 = new javax.swing.JLabel();
        eventCapacityEditTF = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        eventDateEditTF = new javax.swing.JFormattedTextField();
        editEventB = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        eventArtist3EditTF = new javax.swing.JComboBox();
        eventDelete = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        eventSelectorD = new javax.swing.JComboBox();
        deleteEventB = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        artistP = new javax.swing.JPanel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        artistCreate = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        artistNameAddTF = new javax.swing.JTextField();
        artistIdAddTF = new javax.swing.JTextField();
        artistJobAddTF = new javax.swing.JTextField();
        addArtistB = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        artistEdit = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        artistList = new javax.swing.JComboBox();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        artistIdEditTF = new javax.swing.JTextField();
        artistJobEditTF = new javax.swing.JTextField();
        artistNameEditTF = new javax.swing.JTextField();
        editArtistB = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        placeP = new javax.swing.JPanel();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        placeAdd = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        placeNameAddTF = new javax.swing.JTextField();
        placeDeckAddTF = new javax.swing.JTextField();
        placeSectionAddTF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        placeCapacityAddTF = new javax.swing.JTextField();
        createPlaceB = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        placeEdit = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        placeList = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        placeNameEditTF = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        placeDeckEditTF = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        placeSectionEditTF = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        placeCapacityEditTF = new javax.swing.JTextField();
        editPlaceB = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1360, 720));
        setMinimumSize(new java.awt.Dimension(980, 689));
        setPreferredSize(new java.awt.Dimension(1360, 720));

        Bg.setMinimumSize(new java.awt.Dimension(980, 689));
        Bg.setPreferredSize(new java.awt.Dimension(1360, 720));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Admin"));

        jTabbedPane1.setBackground(new java.awt.Color(204, 255, 255));
        jTabbedPane1.setMinimumSize(new java.awt.Dimension(741, 402));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(741, 402));

        jTabbedPane2.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane2StateChanged(evt);
            }
        });

        jLabel12.setText("Nombre Evento");

        jLabel13.setText("Lugar");

        eventPlaceAddTF.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel14.setText("Artistas");

        eventArtist1AddTF.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        eventArtist1AddTF.setPreferredSize(new java.awt.Dimension(163, 20));

        eventArtist2AddTF.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        eventArtist2AddTF.setPreferredSize(new java.awt.Dimension(163, 20));

        eventArtist3AddTF.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        eventArtist3AddTF.setPreferredSize(new java.awt.Dimension(163, 20));
        eventArtist3AddTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventArtist3AddTFActionPerformed(evt);
            }
        });

        jLabel15.setText("Capacidad");

        jLabel16.setText("Fecha y Hora");

        addEventB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        addEventB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addEventBMouseClicked(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setText("Crear");

        javax.swing.GroupLayout addEventBLayout = new javax.swing.GroupLayout(addEventB);
        addEventB.setLayout(addEventBLayout);
        addEventBLayout.setHorizontalGroup(
            addEventBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addEventBLayout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addContainerGap(63, Short.MAX_VALUE))
        );
        addEventBLayout.setVerticalGroup(
            addEventBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addEventBLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout eventCreateLayout = new javax.swing.GroupLayout(eventCreate);
        eventCreate.setLayout(eventCreateLayout);
        eventCreateLayout.setHorizontalGroup(
            eventCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(eventCreateLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(eventCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(eventCreateLayout.createSequentialGroup()
                        .addGroup(eventCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14))
                        .addGap(18, 18, 18)
                        .addGroup(eventCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(eventNameAddTF)
                            .addComponent(eventPlaceAddTF, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(eventCreateLayout.createSequentialGroup()
                                .addComponent(eventArtist1AddTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 58, Short.MAX_VALUE)
                                .addComponent(eventArtist2AddTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 58, Short.MAX_VALUE)
                                .addComponent(eventArtist3AddTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(jLabel15)
                    .addGroup(eventCreateLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(25, 25, 25)
                        .addGroup(eventCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(eventDateAddTF, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(eventCapacityAddTF, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(eventCreateLayout.createSequentialGroup()
                        .addGap(0, 278, Short.MAX_VALUE)
                        .addComponent(addEventB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 273, Short.MAX_VALUE)))
                .addContainerGap())
        );
        eventCreateLayout.setVerticalGroup(
            eventCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(eventCreateLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(eventCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(eventNameAddTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(eventCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(eventPlaceAddTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(eventCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(eventArtist1AddTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eventArtist2AddTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eventArtist3AddTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(eventCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(eventCapacityAddTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(eventCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(eventDateAddTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(addEventB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        jTabbedPane2.addTab("Crear", eventCreate);

        jLabel20.setText("Evento");

        eventSelectorE.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        eventSelectorE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventSelectorEActionPerformed(evt);
            }
        });

        jLabel21.setText("Nombre Evento");

        jLabel22.setText("Lugar");

        eventEditPlaceTF.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel23.setText("Artistas");

        eventArtist1EditTF.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        eventArtist1EditTF.setPreferredSize(new java.awt.Dimension(163, 20));
        eventArtist1EditTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventArtist1EditTFActionPerformed(evt);
            }
        });

        eventArtist2EditTF.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        eventArtist2EditTF.setPreferredSize(new java.awt.Dimension(163, 20));

        jLabel24.setText("Capacidad");

        jLabel25.setText("Fecha y Hora");

        eventDateEditTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventDateEditTFActionPerformed(evt);
            }
        });

        editEventB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        editEventB.setPreferredSize(new java.awt.Dimension(82, 37));
        editEventB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editEventBMouseClicked(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel26.setText("Editar");

        javax.swing.GroupLayout editEventBLayout = new javax.swing.GroupLayout(editEventB);
        editEventB.setLayout(editEventBLayout);
        editEventBLayout.setHorizontalGroup(
            editEventBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editEventBLayout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );
        editEventBLayout.setVerticalGroup(
            editEventBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editEventBLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel26)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        eventArtist3EditTF.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        eventArtist3EditTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventArtist3EditTFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout eventEditLayout = new javax.swing.GroupLayout(eventEdit);
        eventEdit.setLayout(eventEditLayout);
        eventEditLayout.setHorizontalGroup(
            eventEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(eventEditLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(eventEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23)
                    .addComponent(jLabel24)
                    .addComponent(jLabel25)
                    .addComponent(jLabel20))
                .addGap(18, 18, 18)
                .addGroup(eventEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(eventEditLayout.createSequentialGroup()
                        .addGroup(eventEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(eventEditLayout.createSequentialGroup()
                                .addGroup(eventEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(eventDateEditTF, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(eventCapacityEditTF, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(eventEditLayout.createSequentialGroup()
                                .addComponent(eventArtist1EditTF, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                                .addComponent(eventArtist2EditTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)))
                        .addComponent(eventArtist3EditTF, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57))
                    .addComponent(eventSelectorE, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(eventEditNameTF)
                    .addComponent(eventEditPlaceTF, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, eventEditLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(editEventB, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        eventEditLayout.setVerticalGroup(
            eventEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(eventEditLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(eventEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(eventSelectorE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(eventEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(eventEditNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(eventEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addComponent(eventEditPlaceTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(eventEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(eventArtist1EditTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eventArtist3EditTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eventArtist2EditTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(eventEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(eventCapacityEditTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(eventEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(eventDateEditTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(editEventB, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        jTabbedPane2.addTab("Editar", eventEdit);

        jLabel18.setText("Evento");

        eventSelectorD.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        eventSelectorD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventSelectorDActionPerformed(evt);
            }
        });

        deleteEventB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Eliminar");

        javax.swing.GroupLayout deleteEventBLayout = new javax.swing.GroupLayout(deleteEventB);
        deleteEventB.setLayout(deleteEventBLayout);
        deleteEventBLayout.setHorizontalGroup(
            deleteEventBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deleteEventBLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        deleteEventBLayout.setVerticalGroup(
            deleteEventBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deleteEventBLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout eventDeleteLayout = new javax.swing.GroupLayout(eventDelete);
        eventDelete.setLayout(eventDeleteLayout);
        eventDeleteLayout.setHorizontalGroup(
            eventDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(eventDeleteLayout.createSequentialGroup()
                .addGroup(eventDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(eventDeleteLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel18)
                        .addGap(18, 18, 18)
                        .addComponent(eventSelectorD, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(eventDeleteLayout.createSequentialGroup()
                        .addGap(281, 281, 281)
                        .addComponent(deleteEventB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(308, Short.MAX_VALUE))
        );
        eventDeleteLayout.setVerticalGroup(
            eventDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(eventDeleteLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(eventDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(eventSelectorD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 212, Short.MAX_VALUE)
                .addComponent(deleteEventB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );

        jTabbedPane2.addTab("Eliminar", eventDelete);

        javax.swing.GroupLayout eventPLayout = new javax.swing.GroupLayout(eventP);
        eventP.setLayout(eventPLayout);
        eventPLayout.setHorizontalGroup(
            eventPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        eventPLayout.setVerticalGroup(
            eventPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );

        jTabbedPane1.addTab("Evento", eventP);

        jTabbedPane3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane3StateChanged(evt);
            }
        });

        jLabel27.setText("Nombre");

        jLabel28.setText("Ocupación");

        jLabel29.setText("Identificación");

        artistNameAddTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                artistNameAddTFActionPerformed(evt);
            }
        });

        addArtistB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        addArtistB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addArtistBMouseClicked(evt);
            }
        });

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("Añadir");

        javax.swing.GroupLayout addArtistBLayout = new javax.swing.GroupLayout(addArtistB);
        addArtistB.setLayout(addArtistBLayout);
        addArtistBLayout.setHorizontalGroup(
            addArtistBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addArtistBLayout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addComponent(jLabel30)
                .addContainerGap(69, Short.MAX_VALUE))
        );
        addArtistBLayout.setVerticalGroup(
            addArtistBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addArtistBLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jLabel30)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout artistCreateLayout = new javax.swing.GroupLayout(artistCreate);
        artistCreate.setLayout(artistCreateLayout);
        artistCreateLayout.setHorizontalGroup(
            artistCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(artistCreateLayout.createSequentialGroup()
                .addGroup(artistCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(artistCreateLayout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addGroup(artistCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel29)
                            .addComponent(jLabel27)
                            .addComponent(jLabel28))
                        .addGap(18, 18, 18)
                        .addGroup(artistCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(artistNameAddTF)
                            .addComponent(artistJobAddTF)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, artistCreateLayout.createSequentialGroup()
                                .addComponent(artistIdAddTF, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                                .addGap(137, 137, 137))))
                    .addGroup(artistCreateLayout.createSequentialGroup()
                        .addGap(247, 247, 247)
                        .addComponent(addArtistB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(217, Short.MAX_VALUE))
        );
        artistCreateLayout.setVerticalGroup(
            artistCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(artistCreateLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(artistCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(artistNameAddTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(artistCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(artistJobAddTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(artistCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(artistIdAddTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addComponent(addArtistB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Añadir", artistCreate);

        jLabel31.setText("Artista");

        artistList.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        artistList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                artistListActionPerformed(evt);
            }
        });

        jLabel32.setText("Nombre");

        jLabel33.setText("Ocupación");

        jLabel34.setText("Identificación");

        artistIdEditTF.setEnabled(false);

        editArtistB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        editArtistB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editArtistBMouseClicked(evt);
            }
        });

        jLabel35.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel35.setText("Editar");

        javax.swing.GroupLayout editArtistBLayout = new javax.swing.GroupLayout(editArtistB);
        editArtistB.setLayout(editArtistBLayout);
        editArtistBLayout.setHorizontalGroup(
            editArtistBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editArtistBLayout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );
        editArtistBLayout.setVerticalGroup(
            editArtistBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editArtistBLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout artistEditLayout = new javax.swing.GroupLayout(artistEdit);
        artistEdit.setLayout(artistEditLayout);
        artistEditLayout.setHorizontalGroup(
            artistEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(artistEditLayout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addGroup(artistEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel34)
                    .addComponent(jLabel33)
                    .addComponent(jLabel32)
                    .addComponent(jLabel31))
                .addGap(18, 18, 18)
                .addGroup(artistEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(editArtistB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(artistEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(artistList, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(artistNameEditTF)
                        .addComponent(artistJobEditTF, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(artistIdEditTF, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(215, Short.MAX_VALUE))
        );
        artistEditLayout.setVerticalGroup(
            artistEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(artistEditLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(artistEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(artistList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(artistEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(artistNameEditTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(artistEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(artistJobEditTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(artistEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(artistIdEditTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(editArtistB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );

        jTabbedPane3.addTab("Editar", artistEdit);

        javax.swing.GroupLayout artistPLayout = new javax.swing.GroupLayout(artistP);
        artistP.setLayout(artistPLayout);
        artistPLayout.setHorizontalGroup(
            artistPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane3)
        );
        artistPLayout.setVerticalGroup(
            artistPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane3)
        );

        jTabbedPane1.addTab("Artistas", artistP);

        jTabbedPane4.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane4StateChanged(evt);
            }
        });

        jLabel1.setText("Nombre");

        jLabel2.setText("Cubierta");

        jLabel3.setText("Seccion");

        jLabel4.setText("Capacidad");

        placeCapacityAddTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placeCapacityAddTFActionPerformed(evt);
            }
        });

        createPlaceB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        createPlaceB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createPlaceBMouseClicked(evt);
            }
        });

        jLabel5.setText("Crear");

        javax.swing.GroupLayout createPlaceBLayout = new javax.swing.GroupLayout(createPlaceB);
        createPlaceB.setLayout(createPlaceBLayout);
        createPlaceBLayout.setHorizontalGroup(
            createPlaceBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createPlaceBLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel5)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        createPlaceBLayout.setVerticalGroup(
            createPlaceBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createPlaceBLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout placeAddLayout = new javax.swing.GroupLayout(placeAdd);
        placeAdd.setLayout(placeAddLayout);
        placeAddLayout.setHorizontalGroup(
            placeAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(placeAddLayout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addGroup(placeAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(placeAddLayout.createSequentialGroup()
                        .addGroup(placeAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(27, 27, 27)
                        .addGroup(placeAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(placeSectionAddTF, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(placeNameAddTF, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                            .addComponent(placeDeckAddTF)))
                    .addGroup(placeAddLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(placeCapacityAddTF, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, placeAddLayout.createSequentialGroup()
                .addContainerGap(350, Short.MAX_VALUE)
                .addComponent(createPlaceB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(306, 306, 306))
        );
        placeAddLayout.setVerticalGroup(
            placeAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(placeAddLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(placeAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(placeNameAddTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(placeAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(placeDeckAddTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(placeAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(placeSectionAddTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(placeAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(placeCapacityAddTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(createPlaceB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
        );

        jTabbedPane4.addTab("Añadir", placeAdd);

        jLabel6.setText("Lugar");

        placeList.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        placeList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placeListActionPerformed(evt);
            }
        });

        jLabel7.setText("Nombre");

        jLabel8.setText("Cubierta");

        jLabel9.setText("Seccion");

        jLabel10.setText("Capacidad");

        editPlaceB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        editPlaceB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editPlaceBMouseClicked(evt);
            }
        });

        jLabel11.setText("Editar");

        javax.swing.GroupLayout editPlaceBLayout = new javax.swing.GroupLayout(editPlaceB);
        editPlaceB.setLayout(editPlaceBLayout);
        editPlaceBLayout.setHorizontalGroup(
            editPlaceBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editPlaceBLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel11)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        editPlaceBLayout.setVerticalGroup(
            editPlaceBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editPlaceBLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout placeEditLayout = new javax.swing.GroupLayout(placeEdit);
        placeEdit.setLayout(placeEditLayout);
        placeEditLayout.setHorizontalGroup(
            placeEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(placeEditLayout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addGroup(placeEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(placeEditLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addGroup(placeEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(placeDeckEditTF, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(placeSectionEditTF, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(placeCapacityEditTF, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(placeEditLayout.createSequentialGroup()
                        .addGroup(placeEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel6))
                        .addGap(27, 27, 27)
                        .addGroup(placeEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(placeList, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(placeNameEditTF, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(placeEditLayout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(editPlaceB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        placeEditLayout.setVerticalGroup(
            placeEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(placeEditLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(placeEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(placeList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(placeEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(placeNameEditTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(placeEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(placeDeckEditTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(placeEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(placeSectionEditTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(placeEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(placeCapacityEditTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(editPlaceB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );

        jTabbedPane4.addTab("Editar", placeEdit);

        javax.swing.GroupLayout placePLayout = new javax.swing.GroupLayout(placeP);
        placeP.setLayout(placePLayout);
        placePLayout.setHorizontalGroup(
            placePLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane4)
        );
        placePLayout.setVerticalGroup(
            placePLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane4)
        );

        jTabbedPane1.addTab("Lugares", placeP);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 704, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout BgLayout = new javax.swing.GroupLayout(Bg);
        Bg.setLayout(BgLayout);
        BgLayout.setHorizontalGroup(
            BgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BgLayout.createSequentialGroup()
                .addGap(325, 325, 325)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(327, 327, 327))
        );
        BgLayout.setVerticalGroup(
            BgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BgLayout.createSequentialGroup()
                .addContainerGap(124, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(166, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(Bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(Bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void eventDateEditTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventDateEditTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eventDateEditTFActionPerformed

    private void artistNameAddTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_artistNameAddTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_artistNameAddTFActionPerformed

    private void jTabbedPane2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane2StateChanged
        generarListasP2();
    }//GEN-LAST:event_jTabbedPane2StateChanged

    private void eventSelectorDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventSelectorDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eventSelectorDActionPerformed

    private void jTabbedPane3StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane3StateChanged
        List list;
        String[] names;
        if (jTabbedPane3.getSelectedIndex() == 1) {
            list = artistaC.findArtistatEntities();
            names = ArtistatJpaController.listToArrayArtist(list);
            artistList.setModel(new DefaultComboBoxModel(names));
        }
    }//GEN-LAST:event_jTabbedPane3StateChanged

    private void jTabbedPane4StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane4StateChanged
        List list;
        String[] names;
        if (jTabbedPane4.getSelectedIndex() == 1) {
            list = lugarC.findLugartEntities();
            names = LugartJpaController.listToArrayPlace(list);
            placeList.setModel(new DefaultComboBoxModel(names));
        }
    }//GEN-LAST:event_jTabbedPane4StateChanged

    private void createPlaceBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createPlaceBMouseClicked
        Lugart lugar = new Lugart();
        lugar.setNombreLugar(placeNameAddTF.getText());
        lugar.setSeccionLugar(placeSectionAddTF.getText());
        lugar.setCubiertaLugar(placeDeckAddTF.getText());
        lugar.setCapacidadLugar(Integer.parseInt(placeCapacityAddTF.getText()));
        String res = lugarC.create(lugar);
        JOptionPane.showMessageDialog(ha, res);
    }//GEN-LAST:event_createPlaceBMouseClicked

    private void placeCapacityAddTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placeCapacityAddTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_placeCapacityAddTFActionPerformed

    private void placeListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placeListActionPerformed

        Lugart lugar = lugarC.findLugart(placeList.getSelectedIndex() + 1);

        placeNameEditTF.setText(lugar.getNombreLugar());
        placeSectionEditTF.setText(lugar.getSeccionLugar());
        placeDeckEditTF.setText(lugar.getCubiertaLugar());
        placeCapacityEditTF.setText(String.valueOf(lugar.getCapacidadLugar()));
        placeId = lugar.getIdLugar();
    }//GEN-LAST:event_placeListActionPerformed

    private void editPlaceBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editPlaceBMouseClicked

        Lugart lugar = lugarC.findLugart(placeId);
        lugar.setNombreLugar(placeNameEditTF.getText());
        lugar.setSeccionLugar(placeSectionEditTF.getText());
        lugar.setCubiertaLugar(placeDeckEditTF.getText());
        lugar.setCapacidadLugar(Integer.parseInt(placeCapacityEditTF.getText()));
        try {
            lugarC.edit(lugar);
            JOptionPane.showMessageDialog(ha, "Lugar editado correctamente");

        } catch (Exception e) {
        }

    }//GEN-LAST:event_editPlaceBMouseClicked

    private void artistListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_artistListActionPerformed
        String name = artistList.getSelectedItem().toString();
        List<Artistat> list = artistaC.findArtistatEntities();
        Artistat artista = null;

        for (Artistat list1 : list) {
            artista = list1;
            if (artista.getNombreArtista().equals(name)) {
                break;
            }
        }

        artistNameEditTF.setText(artista.getNombreArtista());
        artistJobEditTF.setText(artista.getOcupacionArtista());
        artistIdEditTF.setText(Integer.toString(artista.getIdArtista()));

        artistId = artista.getIdArtista();
    }//GEN-LAST:event_artistListActionPerformed

    private void addArtistBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addArtistBMouseClicked
        Artistat artista = new Artistat();
        artista.setNombreArtista(artistNameAddTF.getText());
        artista.setIdArtista(Integer.parseInt(artistIdAddTF.getText()));
        artista.setOcupacionArtista(artistJobAddTF.getText());
        try {
            artistaC.create(artista);
            JOptionPane.showMessageDialog(ha, "Artista registrado correctamente");

        } catch (Exception e) {

        }

    }//GEN-LAST:event_addArtistBMouseClicked

    private void editArtistBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editArtistBMouseClicked
        Artistat artista = artistaC.findArtistat(artistId);
        artista.setNombreArtista(artistNameEditTF.getText());
        artista.setOcupacionArtista(artistJobEditTF.getText());
        artista.setIdArtista(Integer.parseInt(artistIdEditTF.getText()));
        try {
            artistaC.edit(artista);
            JOptionPane.showMessageDialog(ha, "Artista editado correctamente");
            artistId = artista.getIdArtista();
        } catch (Exception ex) {
            Logger.getLogger(AdminApp.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_editArtistBMouseClicked

    private void addEventBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addEventBMouseClicked
        SimpleDateFormat format1 = new SimpleDateFormat("dd/MM/yyyy");
        Eventot event = new Eventot();
        Lugart lugar = lugarC.findLugart(eventPlaceAddTF.getSelectedIndex() + 1);

        event.setNombreEvento(eventNameAddTF.getText());
        try {
            event.setFechaEvento(format1.parse(eventDateAddTF.getText()));

        } catch (ParseException ex) {
            Logger.getLogger(AdminApp.class.getName()).log(Level.SEVERE, null, ex);
        }

        ArrayList<String> names = new ArrayList<>();
        if (!"N/A".equals(eventArtist1AddTF.getSelectedItem().toString())) {
            names.add(eventArtist1AddTF.getSelectedItem().toString());
        }
        if(!"N/A".equals(eventArtist2AddTF.getSelectedItem().toString())){
            names.add(eventArtist2AddTF.getSelectedItem().toString());
        }
        if(!"N/A".equals(eventArtist3AddTF.getSelectedItem().toString())){
            names.add(eventArtist3AddTF.getSelectedItem().toString());
        }
        

        ArrayList<Artistat> artists = artistaC.searchArtistCB(names);

        eventoC.registerEvent(event, lugar, artists, Integer.parseInt(eventCapacityAddTF.getText()), adminS);
        JOptionPane.showMessageDialog(ha, "Evento creado correctamente");
    }//GEN-LAST:event_addEventBMouseClicked

    private void eventArtist3AddTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventArtist3AddTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eventArtist3AddTFActionPerformed

    private void eventArtist1EditTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventArtist1EditTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eventArtist1EditTFActionPerformed

    private void eventArtist3EditTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventArtist3EditTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eventArtist3EditTFActionPerformed

    //EVENTO DISPARADOR INCIIAL
    private void eventSelectorEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventSelectorEActionPerformed
        SimpleDateFormat format1 = new SimpleDateFormat("dd/MM/yyyy");

        //int[] ids = eventoC.returnIdsEvento(eventSelectorE.getSelectedIndex());
        Eventot event = eventoC.findEventot(EventotJpaController.getIds().get(eventSelectorE.getSelectedIndex()));
        
        ArrayList<Integer> ids = eventoC.buscar_ids_artistas(EventotJpaController.getIds().get(eventSelectorE.getSelectedIndex()));
        int capacidad = eventoC.buscarCapacidad(EventotJpaController.getIds().get(eventSelectorE.getSelectedIndex()));
        ArrayList<String> names = artistaC.findArtistatsNames(ids);
        String[] namesModel = ArtistatJpaController.listToArrayArtist(artistaC.findArtistatEntities());
        int[] indexNames = {0,0,0};
        

        eventEditNameTF.setText(event.getNombreEvento());
        eventDateEditTF.setText(format1.format(event.getFechaEvento()));
        int count = 0;
        for (int i = 0; i < names.size(); i++) {
            for (int j = 0; j < namesModel.length; j++) {
                if(names.get(i)==namesModel[j]){
                    indexNames[count]=j;
                    count++;
                }
            }
        }
        
        eventEditPlaceTF.setModel(new DefaultComboBoxModel(LugartJpaController.listToArrayPlace(lugarC.findLugartEntities())));
        eventArtist1EditTF.setModel(new DefaultComboBoxModel(namesModel));
        eventArtist2EditTF.setModel(new DefaultComboBoxModel(namesModel));
        eventArtist3EditTF.setModel(new DefaultComboBoxModel(namesModel));
        eventArtist1EditTF.setSelectedIndex(indexNames[0]);
        eventArtist2EditTF.setSelectedIndex(indexNames[1]);
        eventArtist3EditTF.setSelectedIndex(indexNames[2]);
        eventCapacityEditTF.setText(""+capacidad);


    }//GEN-LAST:event_eventSelectorEActionPerformed

    private void editEventBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editEventBMouseClicked
        Eventot event = eventoC.findEventot(EventotJpaController.getIds().get(eventSelectorE.getSelectedIndex()));                                      
        SimpleDateFormat format1 = new SimpleDateFormat("dd/MM/yyyy");
        event.setNombreEvento(eventEditNameTF.getText());
        Lugart lugar = lugarC.findLugart(eventPlaceAddTF.getSelectedIndex() + 1);
        try {
            event.setFechaEvento(format1.parse(eventDateEditTF.getText()));
            System.out.println(""+ format1.parse(eventDateEditTF.getText()));
        } catch (ParseException e) {
            System.out.println("Error al registrar fecha: "+e);
        }
        ArrayList<String> names = new ArrayList<>();
        if (!"N/A".equals(eventArtist1EditTF.getSelectedItem().toString())) {
            names.add(eventArtist1EditTF.getSelectedItem().toString());
        }
        if(!"N/A".equals(eventArtist2EditTF.getSelectedItem().toString())){
            names.add(eventArtist2EditTF.getSelectedItem().toString());
        }
        if(!"N/A".equals(eventArtist3EditTF.getSelectedItem().toString())){
            names.add(eventArtist3EditTF.getSelectedItem().toString());
        }
        int capacidad = Integer.parseInt(eventCapacityEditTF.getText());

        ArrayList<Artistat> artists = artistaC.searchArtistCB(names);
        eventoC.editEvent(event, lugar, artists, capacidad);
        JOptionPane.showMessageDialog(ha, "Evento editado correctamente");
        
    }//GEN-LAST:event_editEventBMouseClicked

    private void generarListasP2() {
        List list;
        String[] names;
        if (jTabbedPane2.getSelectedIndex() == 0) {
            list = lugarC.findLugartEntities();
            names = LugartJpaController.listToArrayPlace(list);
            eventPlaceAddTF.setModel(new DefaultComboBoxModel(names));

            list = artistaC.findArtistatEntities();
            names = ArtistatJpaController.listToArrayArtist(list);
            eventArtist1AddTF.setModel(new DefaultComboBoxModel(names));
            eventArtist2AddTF.setModel(new DefaultComboBoxModel(names));
            eventArtist3AddTF.setModel(new DefaultComboBoxModel(names));
        } else if (jTabbedPane2.getSelectedIndex() == 1) {
            list = eventoC.findEventotEntities();
            names = EventotJpaController.listToArrayEvent(list);
            eventSelectorE.setModel(new DefaultComboBoxModel(names));
        } else if (jTabbedPane2.getSelectedIndex() == 2) {
            list = eventoC.findEventotEntities();
            names = EventotJpaController.listToArrayEvent(list);
            eventSelectorD.setModel(new DefaultComboBoxModel(names));
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Bg;
    private javax.swing.JPanel addArtistB;
    private javax.swing.JPanel addEventB;
    private javax.swing.JPanel artistCreate;
    private javax.swing.JPanel artistEdit;
    private javax.swing.JTextField artistIdAddTF;
    private javax.swing.JTextField artistIdEditTF;
    private javax.swing.JTextField artistJobAddTF;
    private javax.swing.JTextField artistJobEditTF;
    private javax.swing.JComboBox artistList;
    private javax.swing.JTextField artistNameAddTF;
    private javax.swing.JTextField artistNameEditTF;
    private javax.swing.JPanel artistP;
    private javax.swing.JPanel createPlaceB;
    private javax.swing.JPanel deleteEventB;
    private javax.swing.JPanel editArtistB;
    private javax.swing.JPanel editEventB;
    private javax.swing.JPanel editPlaceB;
    private javax.swing.JComboBox eventArtist1AddTF;
    private javax.swing.JComboBox eventArtist1EditTF;
    private javax.swing.JComboBox eventArtist2AddTF;
    private javax.swing.JComboBox eventArtist2EditTF;
    private javax.swing.JComboBox eventArtist3AddTF;
    private javax.swing.JComboBox eventArtist3EditTF;
    private javax.swing.JTextField eventCapacityAddTF;
    private javax.swing.JTextField eventCapacityEditTF;
    private javax.swing.JPanel eventCreate;
    private javax.swing.JTextField eventDateAddTF;
    private javax.swing.JFormattedTextField eventDateEditTF;
    private javax.swing.JPanel eventDelete;
    private javax.swing.JPanel eventEdit;
    private javax.swing.JTextField eventEditNameTF;
    private javax.swing.JComboBox eventEditPlaceTF;
    private javax.swing.JTextField eventNameAddTF;
    private javax.swing.JPanel eventP;
    private javax.swing.JComboBox eventPlaceAddTF;
    private javax.swing.JComboBox eventSelectorD;
    private javax.swing.JComboBox eventSelectorE;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JPanel placeAdd;
    private javax.swing.JTextField placeCapacityAddTF;
    private javax.swing.JTextField placeCapacityEditTF;
    private javax.swing.JTextField placeDeckAddTF;
    private javax.swing.JTextField placeDeckEditTF;
    private javax.swing.JPanel placeEdit;
    private javax.swing.JComboBox placeList;
    private javax.swing.JTextField placeNameAddTF;
    private javax.swing.JTextField placeNameEditTF;
    private javax.swing.JPanel placeP;
    private javax.swing.JTextField placeSectionAddTF;
    private javax.swing.JTextField placeSectionEditTF;
    // End of variables declaration//GEN-END:variables
}
