/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frontera;

import java.awt.Color;


/**
 *
 * @author Armageddon132
 */
public class HomeApp extends javax.swing.JFrame {

    /**
     * Creates new form HomeApp
     */
    
    
    
    
    
    private LoginApp login = new LoginApp();
    private AdminApp admin = new AdminApp();
    private ClientApp client = new ClientApp();
    
    
    


    public HomeApp() {
        initComponents();
        login.ha = this;
        admin.ha = this;
        client.ha = this;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        basicP = new javax.swing.JPanel();
        homeP = new ImagePanel("C:\\Users\\Joan\\Documents\\NetBeansProjects\\ActividadesCulturales\\resources\\fondo1.jpg");
        jPanel1 = new javax.swing.JPanel();
        clientB = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        adminB = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(32767, 32767));
        setMinimumSize(new java.awt.Dimension(980, 689));
        setPreferredSize(new java.awt.Dimension(1360, 768));

        basicP.setMinimumSize(new java.awt.Dimension(980, 689));
        basicP.setPreferredSize(new java.awt.Dimension(1360, 720));
        basicP.setLayout(new java.awt.BorderLayout());

        homeP.setMinimumSize(new java.awt.Dimension(980, 689));
        homeP.setPreferredSize(new java.awt.Dimension(1360, 720));

        jPanel1.setBackground(new java.awt.Color(0, 69, 158));
        jPanel1.setMinimumSize(new java.awt.Dimension(980, 102));

        clientB.setBackground(new java.awt.Color(78, 159, 233));
        clientB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        clientB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clientB.setPreferredSize(new java.awt.Dimension(190, 80));
        clientB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clientBMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                clientBMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                clientBMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                clientBMousePressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setText("Cliente");
        jLabel1.setAlignmentY(0.0F);
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
        });

        javax.swing.GroupLayout clientBLayout = new javax.swing.GroupLayout(clientB);
        clientB.setLayout(clientBLayout);
        clientBLayout.setHorizontalGroup(
            clientBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clientBLayout.createSequentialGroup()
                .addContainerGap(66, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(66, Short.MAX_VALUE))
        );
        clientBLayout.setVerticalGroup(
            clientBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, clientBLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        adminB.setBackground(new java.awt.Color(78, 159, 233));
        adminB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        adminB.setToolTipText("");
        adminB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        adminB.setPreferredSize(new java.awt.Dimension(190, 80));
        adminB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminBMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                adminBMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                adminBMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                adminBMousePressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setText("Administrador");
        jLabel2.setToolTipText("");
        jLabel2.setAlignmentY(0.0F);
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
        });

        javax.swing.GroupLayout adminBLayout = new javax.swing.GroupLayout(adminB);
        adminB.setLayout(adminBLayout);
        adminBLayout.setHorizontalGroup(
            adminBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminBLayout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        adminBLayout.setVerticalGroup(
            adminBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminBLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(258, Short.MAX_VALUE)
                .addComponent(adminB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 464, Short.MAX_VALUE)
                .addComponent(clientB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(258, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(clientB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adminB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout homePLayout = new javax.swing.GroupLayout(homeP);
        homeP.setLayout(homePLayout);
        homePLayout.setHorizontalGroup(
            homePLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        homePLayout.setVerticalGroup(
            homePLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homePLayout.createSequentialGroup()
                .addGap(0, 666, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        basicP.add(homeP, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(basicP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(basicP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adminBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminBMouseClicked
        eventClickAdminBB();
    }//GEN-LAST:event_adminBMouseClicked

    private void clientBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clientBMouseClicked
        eventClickClienteBB();
    }//GEN-LAST:event_clientBMouseClicked
    boolean ps = true;
    boolean ps2 = true;
    private void adminBMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminBMouseEntered
        ps=false;
        eventButtonAdminBB();
    }//GEN-LAST:event_adminBMouseEntered

    private void adminBMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminBMouseExited
        ps=true;
        eventButtonAdminBB();
    }//GEN-LAST:event_adminBMouseExited

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        ps=false;
        eventButtonAdminBB();
    }//GEN-LAST:event_jLabel2MouseEntered

    private void clientBMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clientBMouseEntered
        ps2=false;
        eventButtonClienteBB();
    }//GEN-LAST:event_clientBMouseEntered

    private void clientBMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clientBMouseExited
        ps2=true;
        eventButtonClienteBB();
    }//GEN-LAST:event_clientBMouseExited

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        ps2=false;
        eventButtonClienteBB();
    }//GEN-LAST:event_jLabel1MouseEntered

    private void adminBMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminBMousePressed
        Color colorbg = new Color(25,109,185,255);
        adminB.setBackground(colorbg);
    }//GEN-LAST:event_adminBMousePressed

    private void clientBMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clientBMousePressed
        Color colorbg = new Color(25,109,185,255);
        clientB.setBackground(colorbg);
    }//GEN-LAST:event_clientBMousePressed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        eventClickAdminBB();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        eventClickClienteBB();
    }//GEN-LAST:event_jLabel1MouseClicked

    public void eventButtonAdminBB(){
        Color colorbg;
        if(!ps){  
            colorbg = new Color(121,191,255,255);
        }else{  
            colorbg = new Color(78,159,233,255);
        }
        adminB.setBackground(colorbg);
    }
    
    public void eventButtonClienteBB(){
        Color colorbg;
        if(!ps2){  
            colorbg = new Color(121,191,255,255);
        }else{  
            colorbg = new Color(78,159,233,255);
        }
        clientB.setBackground(colorbg);
    }
    
    public void eventClickClienteBB(){
        basicP.setVisible(false);
        basicP.remove(homeP);
        basicP.add(client);
        basicP.setVisible(true);
    }
    
    public void eventClickAdminBB(){
        basicP.setVisible(false);
        basicP.remove(homeP);
        basicP.add(login);
        basicP.setVisible(true);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeApp().setVisible(true);
            }
        });
    }
    
    public javax.swing.JPanel getBasicP(){
        return basicP;
    }
    
    public void setBasicP(javax.swing.JPanel panel){
        basicP.setVisible(false);
        basicP.removeAll();
        basicP.add(panel);
        basicP.setVisible(true);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel adminB;
    private javax.swing.JPanel basicP;
    private javax.swing.JPanel clientB;
    public javax.swing.JPanel homeP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
