/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frontera;

import Control.AdmintController;
import Entidad.Admint;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Armageddon132
 */
public class LoginApp extends javax.swing.JPanel {

    /**
     * Creates new form LoginApp
     */
    public HomeApp ha;
    private AdmintController adminCtrl = new AdmintController();

    public LoginApp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Bg = new ImagePanel("C:\\Users\\Joan\\Documents\\NetBeansProjects\\ActividadesCulturales\\resources\\fondo2.jpg");
        BgLogin = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        userTF = new javax.swing.JTextField();
        passwordTF = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        loginB1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        singUpB = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setMinimumSize(new java.awt.Dimension(980, 689));
        setPreferredSize(new java.awt.Dimension(1360, 720));

        Bg.setMinimumSize(new java.awt.Dimension(980, 689));
        Bg.setPreferredSize(new java.awt.Dimension(1360, 720));

        BgLogin.setBackground(new java.awt.Color(255, 255, 255));
        BgLogin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BgLogin.setMaximumSize(new java.awt.Dimension(530, 490));
        BgLogin.setMinimumSize(new java.awt.Dimension(275, 490));
        BgLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BgLoginMouseClicked(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(25, 109, 185));
        jLabel3.setText("Ingresar");
        jLabel3.setFocusable(false);

        userTF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        userTF.setToolTipText("");
        userTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userTFActionPerformed(evt);
            }
        });

        passwordTF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel1.setText("Usuario");

        jLabel6.setText("Contraseña");

        loginB1.setBackground(new java.awt.Color(25, 109, 185));
        loginB1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        loginB1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginB1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginB1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginB1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginB1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                loginB1MousePressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Ingresar");
        jLabel5.setFocusable(false);
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel5MouseEntered(evt);
            }
        });

        javax.swing.GroupLayout loginB1Layout = new javax.swing.GroupLayout(loginB1);
        loginB1.setLayout(loginB1Layout);
        loginB1Layout.setHorizontalGroup(
            loginB1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginB1Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        loginB1Layout.setVerticalGroup(
            loginB1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginB1Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        singUpB.setBackground(new java.awt.Color(255, 255, 255));
        singUpB.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        singUpB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        singUpB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                singUpBMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                singUpBMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                singUpBMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                singUpBMousePressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(25, 109, 185));
        jLabel4.setText("Registro");
        jLabel4.setFocusable(false);
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
        });

        javax.swing.GroupLayout singUpBLayout = new javax.swing.GroupLayout(singUpB);
        singUpB.setLayout(singUpBLayout);
        singUpBLayout.setHorizontalGroup(
            singUpBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, singUpBLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        singUpBLayout.setVerticalGroup(
            singUpBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(singUpBLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout BgLoginLayout = new javax.swing.GroupLayout(BgLogin);
        BgLogin.setLayout(BgLoginLayout);
        BgLoginLayout.setHorizontalGroup(
            BgLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BgLoginLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BgLoginLayout.createSequentialGroup()
                .addContainerGap(117, Short.MAX_VALUE)
                .addGroup(BgLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel1)
                    .addGroup(BgLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(userTF, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(passwordTF, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(BgLoginLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(BgLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(loginB1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(BgLoginLayout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(singUpB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(117, Short.MAX_VALUE))
        );
        BgLoginLayout.setVerticalGroup(
            BgLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BgLoginLayout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userTF, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordTF, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(loginB1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(singUpB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout BgLayout = new javax.swing.GroupLayout(Bg);
        Bg.setLayout(BgLayout);
        BgLayout.setHorizontalGroup(
            BgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BgLayout.createSequentialGroup()
                .addContainerGap(435, Short.MAX_VALUE)
                .addComponent(BgLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(436, Short.MAX_VALUE))
        );
        BgLayout.setVerticalGroup(
            BgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BgLayout.createSequentialGroup()
                .addContainerGap(124, Short.MAX_VALUE)
                .addComponent(BgLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void singUpBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_singUpBMouseClicked
        eventoRegistrarClick();
    }//GEN-LAST:event_singUpBMouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        eventoRegistrarClick();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void BgLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BgLoginMouseClicked

    }//GEN-LAST:event_BgLoginMouseClicked

    private void loginB1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginB1MouseClicked
        eventLogInClick();
    }//GEN-LAST:event_loginB1MouseClicked

    private void userTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userTFActionPerformed

    boolean ps = true;
    boolean ps2 = true;
    private void loginB1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginB1MouseEntered
        ps = false;
        eventButtonIngresarBB();
    }//GEN-LAST:event_loginB1MouseEntered

    private void loginB1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginB1MouseExited
        ps = true;
        eventButtonIngresarBB();
    }//GEN-LAST:event_loginB1MouseExited

    private void loginB1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginB1MousePressed
        Color colorbg = new Color(78, 159, 233, 255);
        loginB1.setBackground(colorbg);
    }//GEN-LAST:event_loginB1MousePressed

    private void jLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseEntered
        ps = false;
        eventButtonIngresarBB();
    }//GEN-LAST:event_jLabel5MouseEntered

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        eventLogInClick();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void singUpBMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_singUpBMouseEntered
        ps2=false;
        eventButtonRegistrarBB();
    }//GEN-LAST:event_singUpBMouseEntered

    private void singUpBMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_singUpBMouseExited
        ps2=true;
        eventButtonRegistrarBB();
    }//GEN-LAST:event_singUpBMouseExited

    private void singUpBMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_singUpBMousePressed
        ps2=false;
        eventButtonRegistrarBB();
    }//GEN-LAST:event_singUpBMousePressed

    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseEntered
        ps2=false;
        eventButtonRegistrarBB();
    }//GEN-LAST:event_jLabel4MouseEntered

    public void eventLogInClick() {
        Admint admin = new Admint(userTF.getText(), passwordTF.getText());
        String res = adminCtrl.LoginAdmint(admin);
        if (res == "Datos correctos") {
            AdminApp app = new AdminApp();
            app.adminS = adminCtrl.getAdminS();
            ha.setBasicP(app);
        } else {
            JOptionPane.showMessageDialog(ha, res);
        }
    }
    
    public void eventoRegistrarClick(){
        SignUpApp sup = new SignUpApp();
        sup.ha = ha;
        ha.setBasicP(sup);
    }

    public void eventButtonIngresarBB() {
        Color colorbg;
        if (!ps) {
            colorbg = new Color(6, 69, 127, 255);
        } else {
            colorbg = new Color(25, 109, 185, 255);
        }
        loginB1.setBackground(colorbg);
    }
    
    public void eventButtonRegistrarBB() {
        Color colorbg;
        if (!ps2) {
            colorbg = new Color(228, 228, 228, 255);
        } else {
            colorbg = new Color(248, 248, 248, 255);
        }
        singUpB.setBackground(colorbg);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Bg;
    private javax.swing.JPanel BgLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel loginB1;
    private javax.swing.JPasswordField passwordTF;
    private javax.swing.JPanel singUpB;
    private javax.swing.JTextField userTF;
    // End of variables declaration//GEN-END:variables
}
