/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Frontera;

import Control.AdmintController;
import Entidad.Admint;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Armageddon132
 */


public class SignUpApp extends javax.swing.JPanel {
    public HomeApp ha;
    private AdmintController adminC = new AdmintController();
    
    
    /** Creates new form SignUpApp */
    public SignUpApp() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Bg = new ImagePanel("C:\\Users\\Armageddon132\\Documents\\Ingesoft\\ActividadesCulturales\\resources\\fondo2.jpg");
        BgSignUp = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        userTF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        registerB = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        passwordTF = new javax.swing.JPasswordField();
        vPasswordTF = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(980, 689));
        setPreferredSize(new java.awt.Dimension(1360, 720));

        Bg.setMinimumSize(new java.awt.Dimension(980, 689));

        BgSignUp.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("Usuario*");

        jLabel3.setText("Contraseña*");

        jLabel4.setText("Validar Contraseña*");

        registerB.setBackground(new java.awt.Color(255, 51, 0));
        registerB.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        registerB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registerB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerBMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                registerBMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                registerBMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                registerBMousePressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Registrar");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel5MouseEntered(evt);
            }
        });

        javax.swing.GroupLayout registerBLayout = new javax.swing.GroupLayout(registerB);
        registerB.setLayout(registerBLayout);
        registerBLayout.setHorizontalGroup(
            registerBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerBLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel5)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        registerBLayout.setVerticalGroup(
            registerBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registerBLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("Registrarse");

        javax.swing.GroupLayout BgSignUpLayout = new javax.swing.GroupLayout(BgSignUp);
        BgSignUp.setLayout(BgSignUpLayout);
        BgSignUpLayout.setHorizontalGroup(
            BgSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BgSignUpLayout.createSequentialGroup()
                .addContainerGap(78, Short.MAX_VALUE)
                .addGroup(BgSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BgSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(BgSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(vPasswordTF, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(BgSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(userTF, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(BgSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(passwordTF, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(registerB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        BgSignUpLayout.setVerticalGroup(
            BgSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BgSignUpLayout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userTF, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordTF, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vPasswordTF, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(registerB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout BgLayout = new javax.swing.GroupLayout(Bg);
        Bg.setLayout(BgLayout);
        BgLayout.setHorizontalGroup(
            BgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BgLayout.createSequentialGroup()
                .addGap(472, 472, 472)
                .addComponent(BgSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(499, Short.MAX_VALUE))
        );
        BgLayout.setVerticalGroup(
            BgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BgLayout.createSequentialGroup()
                .addContainerGap(142, Short.MAX_VALUE)
                .addComponent(BgSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    
    boolean ps = true;
    
    private void registerBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerBMouseClicked
        eventRegistrarClick();
    }//GEN-LAST:event_registerBMouseClicked

    private void registerBMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerBMouseEntered
        ps=false;
        eventButtonRegistrerBB();
    }//GEN-LAST:event_registerBMouseEntered

    private void registerBMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerBMouseExited
        ps=true;
        eventButtonRegistrerBB();
    }//GEN-LAST:event_registerBMouseExited

    private void registerBMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerBMousePressed
    
    }//GEN-LAST:event_registerBMousePressed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        eventRegistrarClick();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseEntered
        ps=false;
        eventButtonRegistrerBB();
    }//GEN-LAST:event_jLabel5MouseEntered

    public void eventButtonRegistrerBB() {
        Color colorbg;
        if (!ps) {
            colorbg = new Color(225, 19, 5, 255);
        } else {
            colorbg = new Color(255, 51, 0, 255);
        }
        registerB.setBackground(colorbg);
    }
    
    public void eventRegistrarClick(){
        Admint newAdmin = new Admint();
        newAdmin.setNombreAdmin(userTF.getText());
        newAdmin.setContraseniaAdmin(String.valueOf(passwordTF.getPassword()));
        String res = adminC.create(newAdmin, vPasswordTF.getText());
        JOptionPane.showMessageDialog(ha, res);
        if(res=="registro exitoso"){
            LoginApp lg = new LoginApp();
            lg.ha = ha;
            ha.setBasicP(lg);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Bg;
    private javax.swing.JPanel BgSignUp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField passwordTF;
    private javax.swing.JPanel registerB;
    private javax.swing.JTextField userTF;
    private javax.swing.JPasswordField vPasswordTF;
    // End of variables declaration//GEN-END:variables

}
